/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazlabproje;

import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Hp
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginJTabbedPane = new javax.swing.JTabbedPane();
        girisPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kullaniciAdiBolumu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kullaniciSifreBolumu = new javax.swing.JPasswordField();
        girisButton = new javax.swing.JButton();
        kayitPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        kullaniciAdi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        kullaniciMail = new javax.swing.JTextField();
        kayitButton = new javax.swing.JButton();
        kullaniciSifre = new javax.swing.JPasswordField();
        sifrePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        kullaniciAdi2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelMail1 = new javax.swing.JLabel();
        sifremiDegistirButton = new javax.swing.JButton();
        kullaniciEskiSifre = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        kullaniciMail2 = new javax.swing.JTextField();
        kullaniciYeniSifre = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Kullanıcı Adı:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Şifre: ");

        girisButton.setText("Giriş Yap");
        girisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout girisPanelLayout = new javax.swing.GroupLayout(girisPanel);
        girisPanel.setLayout(girisPanelLayout);
        girisPanelLayout.setHorizontalGroup(
            girisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisPanelLayout.createSequentialGroup()
                .addGroup(girisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(girisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(girisButton, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addGroup(girisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(kullaniciAdiBolumu)
                        .addComponent(kullaniciSifreBolumu, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                .addGap(0, 129, Short.MAX_VALUE))
        );
        girisPanelLayout.setVerticalGroup(
            girisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(girisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(girisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kullaniciAdiBolumu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(girisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kullaniciSifreBolumu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(girisButton)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        loginJTabbedPane.addTab("Giriş", girisPanel);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Kullanıcı Adı:");

        kullaniciAdi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Şifre: ");

        jLabelMail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelMail.setText("Mail: ");

        kullaniciMail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        kayitButton.setText("Hesabımı Oluştur");
        kayitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kayitPanelLayout = new javax.swing.GroupLayout(kayitPanel);
        kayitPanel.setLayout(kayitPanelLayout);
        kayitPanelLayout.setHorizontalGroup(
            kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayitPanelLayout.createSequentialGroup()
                .addGroup(kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kayitPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kayitPanelLayout.createSequentialGroup()
                        .addGroup(kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kayitPanelLayout.createSequentialGroup()
                                .addComponent(jLabelMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(kayitPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(51, 51, 51)))
                        .addGroup(kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kayitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kullaniciMail, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(kullaniciSifre))))
                .addGap(0, 118, Short.MAX_VALUE))
        );
        kayitPanelLayout.setVerticalGroup(
            kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kayitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kayitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMail)
                    .addComponent(kullaniciMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kayitButton)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        loginJTabbedPane.addTab("Kayıt Ol", kayitPanel);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Kullanıcı Adı:");

        kullaniciAdi2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Eski Şifre");

        jLabelMail1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelMail1.setText("Yeni Şifre");

        sifremiDegistirButton.setText("Şifremi Değiştir");
        sifremiDegistirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifremiDegistirButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Mail:");

        kullaniciMail2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        javax.swing.GroupLayout sifrePanelLayout = new javax.swing.GroupLayout(sifrePanel);
        sifrePanel.setLayout(sifrePanelLayout);
        sifrePanelLayout.setHorizontalGroup(
            sifrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifrePanelLayout.createSequentialGroup()
                .addGroup(sifrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sifrePanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(kullaniciMail2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sifrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(sifrePanelLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addComponent(kullaniciAdi2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sifrePanelLayout.createSequentialGroup()
                            .addGroup(sifrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(sifrePanelLayout.createSequentialGroup()
                                    .addComponent(jLabelMail1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(sifrePanelLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(51, 51, 51)))
                            .addGroup(sifrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sifremiDegistirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(kullaniciEskiSifre, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(kullaniciYeniSifre, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))))
                .addGap(0, 99, Short.MAX_VALUE))
        );
        sifrePanelLayout.setVerticalGroup(
            sifrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifrePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sifrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kullaniciAdi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sifrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kullaniciEskiSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sifrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullaniciYeniSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMail1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(sifrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kullaniciMail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sifremiDegistirButton)
                .addContainerGap())
        );

        loginJTabbedPane.addTab("Şifreni Değiştir", sifrePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginJTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginJTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kayitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitButtonActionPerformed
        String userName = kullaniciAdi.getText();
        String userPass = new String(kullaniciSifre.getPassword());
        String userMail = kullaniciMail.getText();
        Boolean bilgiDogrulugu = true;
        if (!userMail.contains("@")) {
            JOptionPane.showMessageDialog(null, "Lütfen mailinizi doğru girin.");
            bilgiDogrulugu = false;
        }
        if (bilgiDogrulugu) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = String.format("jdbc:mysql://35.202.83.160:3306/proje");
                Connection conn = DriverManager.getConnection(url, "root", "emre1441.");
                System.out.println("Veritabanına bağlandı.");
                String query = "INSERT INTO users(userName,userPass,userMail) "
                        + "VALUES('" + userName + "','" + userPass + "','" + userMail + "')";
                Statement ifade = conn.createStatement();
                ifade.execute(query);
                conn.close();
                JOptionPane.showMessageDialog(kayitPanel, "Kaydınız Başarıyla Oluşturuldu Giriş Yapabilirsiniz.");
            } catch (SQLException | ClassNotFoundException e) {
                System.out.println("Veritabanına baglanamadı. " + e);
            }

        }
    }//GEN-LAST:event_kayitButtonActionPerformed

    private void girisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisButtonActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = String.format("jdbc:mysql://35.202.83.160:3306/proje");
            Connection conn = DriverManager.getConnection(url, "root", "emre1441.");
            System.out.println("Veritabanına bağlandı.");
            String query = "SELECT userName, userPass"
                    + " FROM users WHERE userName='" + kullaniciAdiBolumu.getText() + "' && userPass='" + new String(kullaniciSifreBolumu.getPassword()) + "'";
            Statement ifade = conn.createStatement();
            ResultSet rs = ifade.executeQuery(query);
            if (rs.next()) {
                while (rs.next()) {
                    String a = rs.getString("userName");
                }
                conn.close();
                JOptionPane.showMessageDialog(null, "Hoşgeldiniz ");
                Dashboard1 dashboard = new Dashboard1();
                dashboard.show();
                Dashboard2 dashboard2 = new Dashboard2();
                dashboard2.show();
                dashboard.setDash2(dashboard2);
                dashboard2.setDash1(dashboard);
                dispose();
                
            } else {
                JOptionPane.showMessageDialog(null, "Kullanıcı adı veya şifre hatalı.");

            }

        } catch (SQLException | ClassNotFoundException e) {
            System.out.println("Veritabanına baglanamadı. " + e);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_girisButtonActionPerformed

    private void sifremiDegistirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifremiDegistirButtonActionPerformed
        String x = new String(kullaniciEskiSifre.getPassword());
        String y = new String(kullaniciYeniSifre.getPassword());
        if (!x.equalsIgnoreCase(y)) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                String url = String.format("jdbc:mysql://35.202.83.160:3306/proje");
                Connection conn = DriverManager.getConnection(url, "root", "emre1441.");
                System.out.println("Veritabanına bağlandı.");
                String query = "SELECT userName, userPass, userMail"
                        + " FROM users WHERE userName='" + kullaniciAdi2.getText() + "' && userPass='" + new String(kullaniciEskiSifre.getPassword()) + "' && userMail='" + kullaniciMail2.getText() + "'";
                Statement ifade = conn.createStatement();
                ResultSet rs = ifade.executeQuery(query);
                if (rs.next()) {
                    String query2 = "UPDATE users SET userPass='" + new String(kullaniciYeniSifre.getPassword()) + "' WHERE userName='" + kullaniciAdi2.getText() + "'";
                    Statement ifade2 = conn.createStatement();
                    ifade2.executeUpdate(query2);
                    conn.close();
                    JOptionPane.showMessageDialog(null, "Şifreniz başarıyla değiştirildi.");

                } else {
                    JOptionPane.showMessageDialog(null, "Kullanıcı adı, mail veya şifre hatalı.");
                    conn.close();
                }

            } catch (SQLException | ClassNotFoundException e) {
                System.out.println("Veritabanına baglanamadı. " + e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Yeni şifre eski şifrenizle aynı olamaz.");
        }

    }//GEN-LAST:event_sifremiDegistirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton girisButton;
    private javax.swing.JPanel girisPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMail1;
    private javax.swing.JButton kayitButton;
    private javax.swing.JPanel kayitPanel;
    private javax.swing.JTextField kullaniciAdi;
    private javax.swing.JTextField kullaniciAdi2;
    private javax.swing.JTextField kullaniciAdiBolumu;
    private javax.swing.JPasswordField kullaniciEskiSifre;
    private javax.swing.JTextField kullaniciMail;
    private javax.swing.JTextField kullaniciMail2;
    private javax.swing.JPasswordField kullaniciSifre;
    private javax.swing.JPasswordField kullaniciSifreBolumu;
    private javax.swing.JPasswordField kullaniciYeniSifre;
    private javax.swing.JTabbedPane loginJTabbedPane;
    private javax.swing.JPanel sifrePanel;
    private javax.swing.JButton sifremiDegistirButton;
    // End of variables declaration//GEN-END:variables
}
